name: webblen
description: Webblen Flutter App

dependencies:

  flutter:
    sdk: flutter

  cloud_firestore: ^0.8.0
  cupertino_icons: ^0.1.2

  flushbar: 0.9.2
  firebase_auth: ^0.5.20
  flutter_swiper: ^1.1.2
  flutter_facebook_login: ^1.1.1
  flutter_google_places_autocomplete: ^0.1.1+1
  flutter_speed_dial: ^1.0.6
  flutter_sparkline: ^0.1.0
  flutter_staggered_grid_view: ^0.2.2
  flutter_statusbarcolor: ^0.1.1

  flutter_calendar:
      git: https://github.com/apptreesoftware/flutter_calendar.git

  firebase_storage: ^1.0.2
  firebase_messaging: ^2.0.0
  font_awesome_flutter: ^8.0.1

  geocoder: ^0.1.1

  image_cropper: ^0.0.6
  image_picker: ^0.4.10

  location: ^1.4.1

  url_launcher: ^3.0.3

#  map_view:
#    git: https://github.com/diegoveloper/flutter_google_map_view.git
#  flutter_twitter_login:
#    git: https://github.com/eudangeld/flutter_twitter_login.git


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/gifs/


  fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Poppins-Regular.ttf
            weight: 400
      - family: Themify
        fonts:
          - asset: assets/fonts/themify.ttf
      - family: LineAwesome
        fonts:
          - asset: assets/fonts/line-awesome.ttf
      - family: Timeburner
        fonts:
          - asset: assets/fonts/timeburnernormal.ttf
          - asset: assets/fonts/timeburnerbold.ttf
            weight: 700