name: webblen
description: Webblen Flutter App

dependencies:
  flutter:
    sdk: flutter

  flutter_sparkline:
    git: https://github.com/mukai154/flutter_sparkline.git

  flutter_staggered_grid_view: ^0.2.2

  firebase_auth: ^0.5.15
  cloud_firestore: ^0.7.4
  firebase_storage: ^1.0.1

  font_awesome_flutter: ^8.0.1

  geocoder: ^0.1.1
  map_view:
    git: https://github.com/diegoveloper/flutter_google_map_view.git
  location: ^1.3.4
  flutter_google_places_autocomplete: ^0.1.0

  flutter_calendar:
    git: https://github.com/apptreesoftware/flutter_calendar.git

  image_picker: ^0.4.6
  image_cropper: ^0.0.5

  flutter_speed_dial: ^1.0.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  flutter_facebook_login: ^1.1.1
  url_launcher: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/gifs/


  fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Poppins-Regular.ttf
            weight: 400
      - family: Themify
        fonts:
          - asset: assets/fonts/themify.ttf
      - family: LineAwesome
        fonts:
          - asset: assets/fonts/line-awesome.ttf
      - family: Timeburner
        fonts:
          - asset: assets/fonts/timeburnernormal.ttf
          - asset: assets/fonts/timeburnerbold.ttf
            weight: 700
