name: webblen
description: Webblen Flutter App

dependencies:

  flutter:
    sdk: flutter

  cloud_firestore: ^0.8.2+3
  cached_network_image: ^0.5.1

  flushbar: ^1.2.0
  firebase_auth: ^0.6.6
  flutter_swiper: ^1.1.4
  flutter_facebook_login: ^1.1.1
  flutter_google_places_autocomplete: ^0.1.3
  flutter_speed_dial: ^1.0.9
  flutter_staggered_grid_view: ^0.2.5

  flutter_twitter_login:
    git: https://github.com/mukai154/flutter_twitter_login.git

  flutter_calendar:
      git: https://github.com/apptreesoftware/flutter_calendar.git

  firebase_storage: ^1.0.4
  firebase_messaging: ^2.1.0
  font_awesome_flutter: ^8.2.0
  firebase_admob: ^0.7.0
  ads:
      git:
        url: git://github.com/mukai154/ads.git

  geocoder: ^0.1.2

  image_cropper: ^0.0.9
  image_picker: ^0.4.10

  location: ^1.4.1

  percent_indicator: ^1.0.12
  url_launcher: ^4.0.3
  carousel_slider: ^1.0.1
  pull_to_refresh: ^1.1.6
  card_settings: ^1.2.4
  flip_box_bar: ^0.2.0
  hidden_drawer_menu: ^0.2.0

  web3dart: ^0.4.5
  video_player: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/gifs/