name: webblen
description: Webblen Flutter App

dependencies:

  flutter:
    sdk: flutter

  cloud_firestore: 0.9.7
  cached_network_image: 0.7.0

  flushbar: 1.3.0
  firebase_auth: 0.8.2
  flutter_swiper: 1.1.6
  flutter_facebook_login: 1.1.1
  flutter_google_places: ^0.2.1
  google_maps_webservice: ^0.0.13
  flutter_staggered_grid_view: 0.2.7

  flutter_twitter_login:
    git: https://github.com/mukai154/flutter_twitter_login.git

  table_calendar: ^1.1.4
  flutter_datetime_picker: ^1.1.6
  datetime_picker_formfield: ^0.1.8
  flutter_tags: "^0.3.0"
  contact_picker: ^0.0.2
  flutter_sms: ^0.2.0
  firebase_dynamic_links: ^0.2.1

  firebase_storage: 2.1.0+1
  firebase_messaging: 4.0.0+1
  font_awesome_flutter: 8.4.0
  firebase_admob: ^0.7.0
  geoflutterfire: ^2.0.3+2

  geocoder: ^0.1.2

  image_cropper: 1.0.0
  image_picker: 0.5.0+9
  flutter_image_compress: ^0.2.4

  location: 2.3.1
  # flutter_background_geolocation: ^0.3.4
  flutter_local_notifications: 0.5.2

  percent_indicator: 1.0.14
  url_launcher: 5.0.2
  carousel_slider: ^1.3.0
  pull_to_refresh: ^1.1.6
  hidden_drawer_menu:  1.0.0
  flutter_masked_text: ^0.8.0
  add_2_calendar: ^1.2.2

#  web3dart: ^0.4.5
#  video_player: ^0.10.0
#  share: ^0.6.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Light.ttf
          weight: 300
        - asset: assets/fonts/Barlow-Regular.ttf
          weight: 400
        - asset: assets/fonts/Barlow-Medium.ttf
          weight: 500

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900